---
apiVersion: v1
kind: Namespace
metadata:
  name: category
  labels:
    istio-injection: enabled

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: category
spec:
  replicas: 2
  selector:
    matchLabels:
      app: category
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: category
    spec:
      containers:
        - name: category
          image: mercari/go-conference-2021-spring-office-hour/category:latest
          imagePullPolicy: Never
          resources:
            limits:
              cpu: 50m
              memory: 50Mi
            requests:
              cpu: 50m
              memory: 50Mi

---
apiVersion: v1
kind: Service
metadata:
  name: category
  namespace: category
spec:
  type: ClusterIP
  selector:
    app: category
  ports:
    - name: grpc
      protocol: TCP
      port: 5000
      targetPort: 5000
